### PR TITLE
Change `depth` to 3 in examples

### LINKED ISSUE #191: Change `depth` to 3 in examples
https://github.com/iotaledger/iota.lib.py/blob/3f452a627233d413269381970058780a09215d64/examples/send_transfer.py#L22

### PR DESCRIPTION
**Pull request by Hribek25**
fixes #191

### CODE REVIEW

**Comment by todofixthis** [comment]
Hey @Hribek25 thanks for working on this!

Looks like there is one test failing; could you have a look at the [Travis CI build result](https://travis-ci.org/iotaledger/iota.lib.py/builds/399907123)?

Once that's addressed, this should be ready to merge 😺

**Comment by Hribek25** [comment]
Hey @todofixthis , thanks for your guidance. 

While changing depth=100 -> depth=3 I was changing it also in test routines and it turned out to not be best idea:) Changes to test routines were reverted back.

**Comment by todofixthis** [comment]
Looks good.  I feel like we should set a default value for `depth` in the routines as well, but maybe we'll make that a separate issue, since it currently doesn't have a default value.

I just changed the target branch to `develop`, which introduced a couple of conflicts (we're currently in the middle of PEP-8-ifying the codebase).  Once those conflicts are resolved, this PR is ready to merge 😺

**Comment by todofixthis** [comment]
Cheers for that!  I will give it a final once-over this weekend 😺

**Comment by todofixthis** [comment]
Looks good.  Thanks @Hribek25 !

**Pull request merged**
