### PR TITLE
Update Discord link to IOTA official one

### PR DESCRIPTION
**Pull request by pcwu**
The previous link is not IOTA official Discord community. Update the link to the official one.

### CODE REVIEW

**Comment by todofixthis** [comment]
Hi Po-Chun!  Good catch; thanks for fixing this!

Could you send me a link to where you found the official Discord URL?  I just need to confirm before I merge this change.

**Comment by pcwu** [comment]
Hello Phoenix,

This link is from the official slack, announcement channel. I copy from Dominik Schiener's post (Last post in this channel)

image

**Comment by todofixthis** [comment]
Thanks for the reference image.  Hm; this is interesting because the IOTA blog has a different URL (https://discord.gg/rx5uu8z):
https://blog.iota.org/iota-trinity-wallet-next-steps-12922a53f8d2

I'll follow up with the IF folks and see what URL we should be using.

**Comment by todofixthis** [comment]
Hey Po-Chun!  I had a quick chat with our Discord account admins and Discord tech support, and it turns out there is currently no "canonical" URL for the IOTA Discord server.

[That might change in the future](https://discordapp.com/partners) though, so I'm going to close this PR for now, but if we do finally get a branded URL (or if the one in the documentation stops working), then let's reopen the PR and get the correct URL in there.

Thank you for suggesting this change!  It certainly spurred me to learn more about how Discord works (:

**Comment by pcwu** [comment]
Hello Phoenix,

Thank you very much for your effort on this small issue.

It seems to me that the link Dominik Schiener provided in Slack maybe is not the real "canonical" URL for the IOTA Discord. But it is still much better to replace the current link with this one. 

The current link in README only has 47 online users now, and the link Dominik Schiener provided has 1,572 online users.

I think it might be better to provide an active community link in README for people who just known IOTA. And since this link just announced by a co-founder, I think it is okay to trust that this community is controlled by the foundation.

But it is just my opinion. I totally accepted the decision you made.

Best regards,
Po-Chun

**Comment by todofixthis** [comment]
Ohh, shoot; I did not realise that the current link is going to the wrong place!

Well... that's embarrassing 😕

Thanks for bearing with me; let's go ahead and merge this change so we can get the correct link out there ASAP.

**Pull request merged**
