### PR TITLE
 Removing transaction symbols from package namespace

### LINKED ISSUE #185: Remove BC symbols from `iota/transaction/__init__.py`
Remove the following symbols from `iota/transaction/__init__.py`:

```python
```

### PR DESCRIPTION
**Pull request by redondo-mk**
Fix #185 . Please review and let me know if I missed something.

### CODE REVIEW

**Comment by todofixthis** [comment]
Hey @redondo-mk thanks so much for working on this!  I will take a look this weekend 😺

**Comment by todofixthis** [comment]
Looks great, thanks @redondo-mk !!

There's a few remaining references hiding out in the `examples` and `docs` directories; would you be willing to have a look when you get a chance?

**Comment by redondo-mk** [comment]
Sorry that I missed that - tests didn't save me there. I belive it should be good now.

**Comment by todofixthis** [comment]
jeje no worries.  Thanks @redondo-mk !!  Gonna give this a final once-over, and then it should be ready to merge.

**Comment by redondo-mk** [comment]
I've tried to update my email address from my first commit in this branch and I've done something wrong. I've created another branch 185_symbols_in_transaction_init2 which has changes relevant to #185. I apologize for inconvenience!

**Pull request closed without merging**
