### PR TITLE
Added a check tox env that check-manifest, flake8 and isort

### PR DESCRIPTION
**Pull request by euri10**
(the latest not activated yet, tbc)
Added missing files to MANIFEST.in
Configured flake8 in setup.cfg to authorize 120 chars line-length, how
gentle !
Fixed numerous non-PEP8 compliant spots, in iota / test and examples
folder (ugly commenting of numerous useless imports to make sure it
doesn't break anything, which doesn't seem to be the case so far)

just realize I may have better done that from dev branch....

### CODE REVIEW

**Comment by todofixthis** [comment]
Hey @euri10.  Thanks for your pull request!!

I really like this idea, especially fixing the metadata and automating the checks!

I went ahead and changed the target branch to `develop`.  Unfortunately, that caused a bunch of conflicts to appear.

Have a look at #147 — maybe you can collaborate with @HerrMuellerluedenscheid and @miili .

**Comment by euri10** [comment]
Sounds great, will rebranch on dev tomorrow or Sunday.

Will add the docstrings check also, might be useful.

Before tackling isort I'd love to have someone explainlikeimfive the import
situation, I flagged rightfully many unused import as noqa:f401 but maybe
there's a better alternative.

And while I think about it, the docstrings will also need à cleaned
indentation, I left them as it's no big deal.

Gosh, those 2 space indentation made me think you work for Google, don't
you ? ;)



Le 26 janv. 2018 22:52, "Phoenix" <notifications@github.com> a écrit :

Hey @euri10 <https://github.com/euri10>. Thanks for your pull request!!

I really like this idea, especially fixing the metadata and automating the
checks!

I went ahead and changed the target branch to develop. Unfortunately, that
caused a bunch of conflicts to appear.

Have a look at #147 <https://github.com/iotaledger/iota.lib.py/pull/147> —
maybe you can collaborate with @HerrMuellerluedenscheid
<https://github.com/herrmuellerluedenscheid> and @miili
<https://github.com/miili> .

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iotaledger/iota.lib.py/pull/148#issuecomment-360914453>,
or mute the thread

**Comment by HerrMuellerluedenscheid** [comment]
Hey @euri10, have a look also at #146 where we discussed already a few points regarding pep8 details. We'd.be glad to have you on board to finish the pep8 stylings soon :)

**Comment by todofixthis** [comment]
chur chur

## Imports
If the import appears in an `__init__.py`, then it's probably just an attempt to flatten the namespace a bit.

E.g., it's convenient for developers to do `from iota import TryteString` rather than `from iota.types import TryteString`, etc.

There's also an import in `iota/crypto/__init__.py` that tries to import the `Curl` class from the [ccurl extension](https://github.com/todofixthis/pyota-ccurl), but if the extension is not installed, it will fall back to the pure-Python (slower) implementation.

If there are any other imports that fail the check, let me know, and I can probably provide more context.

## Docstrings
The docstrings should use reStructuredText (some IDEs, such as PyCharm, know how to render them).  reStructuredText traditionally uses 3-space indents, but it will work just fine with 2-si, 4-si, etc.  Feel free to re-indent those as well (:

## Do I work for Google?
jajaja If only, if only.  I just like the horizontally-compressed look; it requires my eyes to do less horizontal scanning to read the code (or at least, I think it does; I haven't exactly measured...).

But, PEP-8 (as well as a number of PyOTA community members!) says 4-space indents, so I'm prefectly happy to switch.

**Comment by HerrMuellerluedenscheid** [comment]
Just had a closer look at you pr. Are you done with all modules already in terms of pep8?

**Comment by euri10** [comment]
Yep, but on wrong branch))

I'll definitely look at both issues you linked, sorry I'm brand new here
and just didn't take the time to properly read,...

Now it's getting late here, happy to continue the exiting style discussion
later on !



Le 26 janv. 2018 23:18, "Marius Kriegerowski" <notifications@github.com> a
écrit :

Just had a closer look at you pr. Are you done with all modules already in
terms of pep8?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iotaledger/iota.lib.py/pull/148#issuecomment-360919936>,
or mute the thread

**Comment by miili** [comment]
please start watching this repo

**Comment by euri10** [comment]
I put the changes to develop  on my fork and dunno if it's possible to keep same PR now that it's on another branch also on my side :)

Added docs checking too and cleant some old links along the way now that linkcheck is enabled.

Read #147 and realize I commented most of the typing import because they're unused and flake8 complained, there's probably a way to keep them without adding for each and every one a noqa:f401

**Comment by miili** [comment]
Edit PR, change base.

**Comment by todofixthis** [comment]
Hey guys.  Really appreciate your hard work on this!  This branch has drifted quite a bit, so I'd like to close this PR and propose a new course of action.

I've also started working on progressively migrating everything over to PEP-8; I should have that wrapped up by the end of the week.  Once that is wrapped up, let's switch focus to adding flake8 (and maybe mypy?) checks to `.travis.yml` and cleaning up any outstanding formatting issues, and then we can finally close #145 😺 

I hate to discard all the hard work you've put into reformatting the code for PEP-8, but I think that the sheer scope of that undertaking was making the process take a lot longer than anybody wanted it to.  So, I'll tackle the boring stuff (reformatting the code), and if you're up for it, you can take on the interesting stuff (setting up automatic checks during the build process and addressing tricky warnings).

**Pull request closed without merging**
